package compilador.sintatico;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int MOD = 14;
  public static final int MENOS = 4;
  public static final int ELSE = 18;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int WHILE = 19;
  public static final int MENOSMENOS = 16;
  public static final int SEMI = 2;
  public static final int LOWER_THAN_ELSE = 21;
  public static final int IF = 17;
  public static final int POT = 12;
  public static final int LPAREN = 7;
  public static final int LBRACE = 9;
  public static final int ID = 23;
  public static final int ATRIB = 11;
  public static final int MAIS = 3;
  public static final int EOF = 0;
  public static final int MENOSUNIT = 6;
  public static final int DIV = 13;
  public static final int NUMERO = 22;
  public static final int error = 1;
  public static final int MAISMAIS = 15;
  public static final int VEZES = 5;
  public static final int FOR = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "MENOSUNIT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ATRIB",
  "POT",
  "DIV",
  "MOD",
  "MAISMAIS",
  "MENOSMENOS",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "LOWER_THAN_ELSE",
  "NUMERO",
  "ID"
  };
}

